name: Stylelint

on: [push]

jobs:
  format:
    name: Stylelint

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run Stylelint
        run: yarn stylelint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Fixing code styling via Stylelint'
