name: Run tests

on: [push]

jobs:
  tests:
    name: Run tests

    # https://github.com/actions/runner-images/tree/main/images/linux
    runs-on: ubuntu-latest

    steps:
      # https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE laravel_inertia_vue_template' -uroot -proot

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install composer dependencies
        run: composer install -n --prefer-dist
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Prepare Laravel application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Set up Node.js
        uses: actions/setup-node@v3

      # I could skip this step (and the previous) if I committed compiled assets to the repo
      - name: Compile front-end assets
        run: |
          yarn --version
          yarn install --frozen-lockfile
          yarn build

      - name: Run tests
        run: php artisan test
